### PR TITLE
Prettier

### PR DESCRIPTION
**Pull request by webdev03**
I saw you all are making formatting PRs so I decided to make a dedicated configuration so that nobody starts fighting over tabs VS spaces. You can change anything. _And @JaydenDev don't get angry and start spamming_

### CODE REVIEW

**Comment by webdev03** [comment]
I didn't commit my lockfile since I didn't know which package manager you like, pnpm or yarn or npm. _and JaydenDev stop saying that pnpm is unofficial when it is included with corepack_

**Comment by webdev03** [comment]
Tell me before merging if you want an action to automatically format, I would make this but I don't know which manager you want to use

**Comment by Mbrick2** [comment]
thanks

**Comment by Mbrick2** [comment]
why is it closed

**Pull request closed without merging**
