### PR TITLE
Code Cleaning [Optional]

### PR DESCRIPTION
**Pull request by JaydenDev**
This PR does the following:

Fix Indention

### CODE REVIEW

**Comment by LankyBox01** [comment]
i just

**Comment by LankyBox01** [comment]
i finished writing a new plan

**Comment by LankyBox01** [comment]
please check issues and give your opinion

**Comment by webdev03** [comment]
Why not Prettier, if you're going to "fix styling" anyways?

**Comment by JaydenDev** [comment]
> Why not Prettier, if you're going to "fix styling" anyways?

Styling is the destroyer of all good code.

**Comment by JaydenDev** [comment]
@LankyBox01 Don't make the same mistake, prettier broke freecat TWICE!!

**Comment by JaydenDev** [comment]
@webdev03 Prettier breaks code instead of fixing it.

**Comment by webdev03** [comment]
Prettier never was meant to fix code
It is meant to style it
Just because you have a bad experience with it that is probably related to something else doesn't mean that it's bad

**Comment by webdev03** [comment]
If you have a bug with it, report it to the devs. Open source!

**Comment by JaydenDev** [comment]
> If you have a bug with it, report it to the devs. Open source!

Prettier sucks, don't use it ignore @webdev03

**Comment by webdev03** [comment]
I'll continue to use it.

**Comment by JaydenDev** [comment]
@webdev03 if you use it in @LankyBox01's repositories OR MINE, you will be the one finding a fix. It's a guarantee it'll break it.

**Comment by webdev03** [comment]
Sure. Anyways let's stop spamming

**Pull request merged**
