### PR TITLE
Reformatted and optimized code.

### PR DESCRIPTION
**Pull request by Steve0Greatness**
I just reformatted the code, and optimized it too.

If you'd like to see this working, you can find it on my [Replit](https://scratch-trust.stevesgreatness.repl.co/)

(Also, I'd just like to say, if there's a rule where there needs to be an issue for a PR, then you should add a `CONTRIBUTING.md` into you're `.github` folder)
(Oh, and I fixed the dashboard... forgot to add that in.)

### CODE REVIEW

**Comment by LankyBox01** [comment]
you poofed the dashboard
```
ForumsFeed Dashboard
Logged in as username=LankyBox01

Progress
Loading...  Loading...
```

These values don't show up anymore, and I'm logged in as username=LankyBox01??

**Comment by LankyBox01** [comment]
When you do changes, you need to note them.
I need to treat the first prompt as a cookie object, because i will be adding more functions that require multiple cookies.

**Comment by Steve0Greatness** [comment]
@LankyBox01, do they need to be stored in cookies? Local storage and session storage are way easier to use, and I don't really think you need to store any sensitive user-data.

> you poofed the dashboard
> 
> ```
> ForumsFeed Dashboard
> Logged in as username=LankyBox01
> 
> Progress
> Loading...  Loading...
> ```
> 
> These values don't show up anymore, and I'm logged in as username=LankyBox01??

I didn't "poof"(?) it. Nobody's going to immediately think of putting in `username=[their username]` when it prompts them.

> When you do changes, you need to note them.

Great, could you make a `CONTRIBUTING.md` and add that to it? Or at least make a pull request template?

>I need to treat the first prompt as a cookie object, because i will be adding more functions that require multiple cookies.

???

**Comment by LankyBox01** [comment]
> @LankyBox01, do they need to be stored in cookies? Local storage and session storage are way easier to use, and I don't really think you need to store any sensitive user-data.
> 
> > you poofed the dashboard
> > ```
> > ForumsFeed Dashboard
> > Logged in as username=LankyBox01
> > 
> > Progress
> > Loading...  Loading...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > These values don't show up anymore, and I'm logged in as username=LankyBox01??
> 
> I didn't "poof"(?) it. Nobody's going to immediately think of putting in `username=[their username]` when it prompts them.

This is for developing tests, of course it is gonna be changed

**Comment by Steve0Greatness** [comment]
> This is for developing tests, of course it is gonna be changed

If you really want to use cookies, then I can make it use cookies again.

**Comment by JaydenDev** [comment]
@LankyBox01 How exactly are you uploading code, if you are doing copy paste from vscode I'd highly recommend using Git or GitHub desktop.

**Comment by Steve0Greatness** [comment]
@LankyBox01, I made it so that cookies are used instead of local/session storage.

**Comment by LankyBox01** [comment]
> @LankyBox01 How exactly are you uploading code, if you are doing copy paste from vscode I'd highly recommend using Git or GitHub desktop.

bruh
I'M ON MOBILE
I don't use vscode

imagine being that dumb that you don't know how to stitch vscode with github :facepalm:

**Comment by JaydenDev** [comment]
> > @LankyBox01 How exactly are you uploading code, if you are doing copy paste from vscode I'd highly recommend using Git or GitHub desktop.
> 
> bruh
> I'M ON MOBILE
> I don't use vscode
> 
> imagine being that dumb that you don't know how to stitch vscode with github :facepalm: 

Was trying to help and this is what you do?

**Comment by JaydenDev** [comment]
You didn't say you were on mobile either

**Comment by JaydenDev** [comment]
This is definitely not the right way to maintain a repository. You deny like half the PRs. All the ones that get accepted are yours.

**Comment by Steve0Greatness** [comment]
@LankyBox01, could you merge this?

**Comment by LankyBox01** [comment]
@Steve0Greatness script.js is conflicting

**Comment by Steve0Greatness** [comment]
> @Steve0Greatness script.js is conflicting

Resolved 😀

**Comment by LankyBox01** [comment]
looks good to me

**Pull request merged**
