### PR TITLE
Check if the user exists before getting trust level

### LINKED ISSUE #13: Check if the user exists before getting the level
```
function getworth(username) {
 fetch("https://scratchdb.lefty.one/v3/forum/user/info/" + encodeURIComponent(username))
 .then(function(response) {
  if (!response.ok) {
   alert(username+" is not on Scratch!");
   return;
  }
  fetch("https://scratchdb.lefty.one/v3/forum/user/info/" + encodeURIComponent(username))
  .then(response => response.json())
  .then(data => waitForElement(data.counts.total.count));
 });
}
```

By [@mybearworld](https://scratch.mit.edu/users/mybearworld) on [this post](https://scratch.mit.edu/discuss/topic/568146/?page=5#post-5904115)

### PR DESCRIPTION
**Pull request by LankyBox01**
Fix #13

### CODE REVIEW

**Review by webdev03 — CHANGES_REQUESTED** [review]
Why two fetch requests to the same endpoint?

**Comment by JaydenDev** [comment]
The function just won't work and there will be no output if the username is invalid, this really isn't a bug that needs fixing or a bug at all. It's fine as is.

**Comment by webdev03** [comment]
Did you know that you can chain `.then` or use async/await ?

**Comment by JaydenDev** [comment]
Can you check if b = null (nothing/undefined). Meaning it couldn't find the information, and have it run
```js
alert("An Unknown Error Occured")
```

**Comment by JaydenDev** [comment]
@webdev03 would work right?

**Comment by JaydenDev** [comment]
I guess this PR is to stop the function from running at all if the user doesn't exist.

**Comment by JaydenDev** [comment]
Now the question is, @LankyBox01; Why you are making a PR in your own repository.

**Comment by JaydenDev** [comment]
I'm testing this PR...
It does!

**Comment by webdev03** [comment]
Making a PR in your own repo is fine. It's a common practise.

**Comment by webdev03** [comment]
```js
function getworth(username) {
 fetch("https://scratchdb.lefty.one/v3/forum/user/info/" + encodeURIComponent(username))
 .then(function(response) {
  if (!response.ok) {
   alert(username +" is not on Scratch!");
   return;
  }
  return response.json()
  }
  .then(data => waitForElement(data.counts.total.count));
 });
```

**Comment by LankyBox01** [comment]
> Why two fetch requests to the same endpoint?

I didn't make this. Mybearworld did.

**Comment by LankyBox01** [comment]
> Now the question is, @LankyBox01; Why you are making a PR in your own repository?

Bruh :facepalm:

So that others can test it and tell me if there are issues. I don't just add the commits directly into the repo without changing, there are people on my site live.

**Comment by LankyBox01** [comment]
https://scratch.mit.edu/discuss/topic/568146/?page=6#post-5905454

**Comment by JaydenDev** [comment]
I never make PRs in my own repos and I've had no issues
https://jaydendev.github/searchocean see!?

**Comment by LankyBox01** [comment]
> I never make PRs in my own repos and I've had no issues https://jaydendev.github.io/searchocean see!?

bruh
I'm gonna be honest here
you act like you're 10
seriously

**Comment by JaydenDev** [comment]
> > I never make PRs in my own repos and I've had no issues https://jaydendev.github.io/searchocean see!?
> 
> bruh I'm gonna be honest here you act like you're 10 seriously

Making PRs in your OWN repo that you have write access to? I don't think anybody else does that.

**Comment by LankyBox01** [comment]
> > > I never make PRs in my own repos and I've had no issues https://jaydendev.github.io/searchocean see!?
> > 
> > 
> > bruh I'm gonna be honest here you act like you're 10 seriously
> 
> Making PRs in your OWN repo that you have write access to? I don't think anybody else does that.

It's a common practice when there are others contributing to the repo. See? People optimized the code of this pr before i actually added it. It is useful.

And if you have a problem with me doing PRs...

**Pull request closed without merging**
