### PR TITLE
Add "Thank you message"

### PR DESCRIPTION
**Pull request by Mbrick2**
It uses scratch usernames

### CODE REVIEW

**Comment by Mbrick2** [comment]
Who else is a contrib.
Is `mybearworld` ?

**Comment by JaydenDev** [comment]
your PR doesn't work
```
Uncaught ReferenceError: getworth is not defined
```

**Comment by webdev03** [comment]
Why am I in the list though?

**Comment by LankyBox01** [comment]
^^
I'll add this separately, just make an issue.

**Pull request closed without merging**
