### PR TITLE
Light and Dark Scratch Themes

### PR DESCRIPTION
**Pull request by JaydenDev**
**WORK IN PROGRESS**

### CODE REVIEW

**Comment by JaydenDev** [comment]
A button to switch themes idk how to do

**Comment by JaydenDev** [comment]
I don't think this will work entirely, it should tho.

**Comment by LankyBox01** [comment]
tests?

**Comment by JaydenDev** [comment]
> tests?

I've tested it fully
@LankyBox01 
It does work

**Comment by JaydenDev** [comment]
@LankyBox01 why did you close the PR?

**Pull request closed without merging**
